version: '3.8'

services:
  custom-postgres:
    image: postgres
    container_name: liquibase-user-postgres
    ports:
      - '5437:5432'
    environment:
      - POSTGRES_USER=mahammad
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user-db
    volumes:
      - ../../docker-volumes/bank-postgres:/var/lib/postgresql/data
