version: '3.8'

services:
  custom-postgres:
    image: postgres
    container_name: user-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=mahammad
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user-db
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db: