spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml
    default-schema: liquibase
    database-change-log-table: database_changelog
    database-change-log-lock-table: database_changelog_lock